### ISSUE TITLE
team_test.py issues

### ISSUE THREAD

**Issue by chaiyawahoo** [MakeSchool-Tutorials/Superhero-Team-Dueler#15]
On line 4, `team_test.py` tries to run:
```python
import superheroes
```
however, superheroes is not a file that exists. This can be avoided by either adding a file, `superheroes.py`, and appending these lines:
```python
from ability import Ability
from weapon import Weapon
from armor import Armor
from hero import Hero
from team import Team
```
or replacing `import superheroes` with the lines above and omitting `superheroes.` from most lines. The easiest way I found to avoid this issue was just to add the `superheroes.py` file.

---
On line 224 in `team_test.py`, the `test_armor` function does not pass a `damage_amt` parameter to `armor.defend()`, which is required. This can be avoided by either passing an arbitrary integer or giving `damage_amt` a default value. Either way, `test_armor` seems pointless as it tests the armor of the same hero (that has no armor, therefore resulting in a value of 0) 500 times. However, I believe the intended solution is to replace the function as follows:
```python
def test_armor():
    armor = superheroes.Armor("The Ring", 200)
    for _ in range(0, 500):
        defense = armor.block()
        assert (defense <= 200 and defense >= 0)
```
---
However, a similar issue surfaces on line 246 in the `test_hero_defense` function, where `jodie.defend()` does not receive a `damage_amt` value. The best solutions to this would be passing the same value as the armor to `jodie.defend()` (in this case, making it `jodie.defend(30)`) to pass the assert, or adding a random damage variable and passing that, changing the function to look like:
```python
def test_hero_defense():
    jodie = superheroes.Hero("Jodie Foster")
    gauntlets = superheroes.Armor("Gauntlets", 30)
    jodie.add_armor(gauntlets)
    damage = random.randint(0, 200) # 200 is arbitrary
    defense = jodie.defend(damage)
    assert defense >= damage-30 and defense <= damage
```
Again, the issue occurs on line 264. The best solution I found was just to pass `strength` as the  `damage_amt` parameter for `athena.defend()`. This is because extra calculations are made with the resulting value. The same thing happens on line 295. This makes be believe the best solution is to just to change the beginning of the `Hero.defend()` method in `hero.py` to look like the following:
```python
def defend(self, damage_amt=None):
    if damage_amt == None:
        damage_amt = 0
        for armor in self.armors:
            damage_amt += armor.max_block
```
This change avoids changing lines 246, 264, 295, and any other lines I didn't get to before changing the `Hero.defend()` method in the `team_test.py` file. It seems to fix any other issues regarding the `Hero.defend()` method for tests.

**Comment by ibirnam** [comment]
Thanks @chaiyawahoo - just fixed this issue now!
